function defaults = modeParamDefaults(lModes,freqRange)
%MODEPARAMDEFAULTS PARAM defaults (for ads.nast.writeParams) of the modes /
%frequency range of interest. An empty freqRange leaves out LFREQ/HFREQ.
if isempty(freqRange)
    fr = {[],[]};
else
    fr = num2cell(freqRange(1:2));
end
defaults = {...
    'LMODES','i',lModes;...
    'LMODESFL','i',lModes;...
    'LFREQ','r',fr{1};...
    'HFREQ','r',fr{2};...
    'LFREQFL','r',fr{1};...
    'HFREQFL','r',fr{2}};
end
